on:
  pull_request:
  push:
    branches:
      - master

name: Continuous integration

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        name: fmt
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: install cargo-hack
        with:
          command: install
          args: cargo-hack

      - uses: actions-rs/cargo@v1
        name: hack check
        with:
          command: hack
          args: check --all --ignore-private --each-feature --no-dev-deps

      - uses: actions-rs/cargo@v1
        name: check
        with:
          command: check
          args: --all --all-targets --all-features

      - uses: actions-rs/cargo@v1
        name: test
        with:
          command: test
          args: --all

      - uses: actions-rs/cargo@v1
        name: clippy
        with:
          command: clippy
          args: -- -D warnings
